name: Nightly Sync of content

on:
  schedule:
  - cron: '0 3 * * *' # run daily at 3am

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Set safe directory
        run: git config --global --add safe.directory /.github/workspace

      - name: Install
        run: npm ci

      - name: Collect latest releases
        run: npm run build

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            data:
              - 'data/**'

      - name: Commit changes
        if: steps.changes.outputs.data == 'true'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "feat: Nightly Sync"

      - name: Bump the version
        if: steps.changes.outputs.data == 'true'
        run:
          npm version patch

      - name: Push changes
        # Only run this on the main nodejs repo and not forks, and only if there are changes to the actual data
        if: ${{ (github.repository == 'chicoxyzzy/node-releases') && (steps.changes.outputs.data == 'true') }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Publish to npm
        # Only run this on the main nodejs repo and not forks, and only if there are changes to the actual data
        if: ${{ (github.repository == 'chicoxyzzy/node-releases') && (steps.changes.outputs.data == 'true') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

